# Generated by Django 3.1.2 on 2020-10-20 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AssetID', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssetMonitoredInfoTimeSeries_000001',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(null=True)),
                ('datahora', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Label', models.CharField(max_length=100, null=True)),
                ('value_measure', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='novatabela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('datahora', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Point', models.CharField(max_length=100, null=True)),
                ('imagem', models.FileField(null=True, upload_to='documents/')),
                ('Cell', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SensorID', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VariableTypeLib',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IoTDeviceID', models.BigIntegerField(null=True)),
            ],
        ),
    ]
