# Generated by Django 3.1.2 on 2020-10-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_csvfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='points',
            name='coment',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
