# Generated by Django 3.1.2 on 2020-10-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_points_coment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
