# Generated by Django 3.1.2 on 2020-10-27 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectVehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_project', models.CharField(max_length=100, null=True)),
                ('description_project', models.CharField(max_length=500, null=True)),
                ('user_create', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SectionVehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_section', models.CharField(max_length=100, null=True)),
                ('projectID', models.FloatField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Asset',
        ),
        migrations.DeleteModel(
            name='AssetMonitoredInfoTimeSeries_000001',
        ),
        migrations.DeleteModel(
            name='novatabela',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Sensor',
        ),
        migrations.DeleteModel(
            name='VariableTypeLib',
        ),
        migrations.RenameField(
            model_name='points',
            old_name='Cell',
            new_name='cell',
        ),
        migrations.RenameField(
            model_name='points',
            old_name='Point',
            new_name='label_point',
        ),
        migrations.AddField(
            model_name='points',
            name='number_point',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='points',
            name='projectID',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='points',
            name='sectionID',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='points',
            name='value_measure',
            field=models.FloatField(null=True),
        ),
    ]
