# Generated by Django 3.1.2 on 2020-10-27 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0005_auto_20201027_0053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectvehicle',
            name='description_project',
        ),
    ]
