# Generated by Django 3.1.2 on 2020-10-27 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0006_remove_projectvehicle_description_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectvehicle',
            name='user_create',
        ),
    ]
