# Generated by Django 3.1.2 on 2020-10-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0008_auto_20201027_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='points',
            name='value_measure',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
