# Generated by Django 3.1.2 on 2020-10-27 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0009_auto_20201027_0738'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Points',
            new_name='Points1',
        ),
    ]
