# Generated by Django 3.1.2 on 2020-10-27 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0010_auto_20201027_1007'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Points1',
            new_name='Points',
        ),
    ]
