# Generated by Django 3.1.2 on 2021-03-14 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0011_auto_20201027_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='points',
            name='coment',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='points',
            name='label_point',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
