# Generated by Django 3.1.2 on 2021-03-14 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cami', models.CharField(max_length=100, null=True)),
                ('pfi', models.CharField(max_length=100, null=True)),
                ('metier', models.CharField(max_length=100, null=True)),
                ('gains_time', models.FloatField(null=True)),
                ('gains_money', models.FloatField(null=True)),
                ('duration', models.FloatField(null=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('day', models.FloatField(null=True)),
                ('month', models.FloatField(null=True)),
            ],
        ),
    ]
