# Generated by Django 3.1.2 on 2021-03-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atelier', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imersion',
            name='day',
        ),
        migrations.RemoveField(
            model_name='imersion',
            name='month',
        ),
        migrations.AddField(
            model_name='imersion',
            name='date',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='imersion',
            name='time_initial',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
