# Generated by Django 3.1.2 on 2021-03-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atelier', '0004_auto_20210315_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imersion',
            name='date',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
