# Generated by Django 3.1.2 on 2021-04-20 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atelier', '0005_auto_20210315_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dojo_imersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100, null=True)),
                ('UET', models.CharField(max_length=100, null=True)),
                ('duration', models.FloatField(null=True)),
                ('module', models.CharField(max_length=500, null=True)),
                ('date', models.CharField(max_length=30, null=True)),
                ('time_initial', models.CharField(max_length=30, null=True)),
                ('status', models.CharField(max_length=30, null=True)),
                ('nota', models.FloatField(null=True)),
            ],
        ),
    ]
