# Generated by Django 3.1.2 on 2021-04-20 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atelier', '0006_dojo_imersion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dojo_imersion',
            name='duration',
        ),
    ]
