# Generated by Django 3.1.2 on 2021-04-20 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atelier', '0007_remove_dojo_imersion_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo_imersion',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='dojo_imersion',
            name='module',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
