# Generated by Django 3.1.2 on 2021-04-23 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atelier', '0008_auto_20210420_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo_imersion',
            name='gabarito0',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='dojo_imersion',
            name='gabarito1',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='dojo_imersion',
            name='gabarito2',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='dojo_imersion',
            name='gabarito3',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='dojo_imersion',
            name='gabarito4',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='dojo_imersion',
            name='gabarito5',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='dojo_imersion',
            name='gabarito6',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='dojo_imersion',
            name='gabarito7',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='dojo_imersion',
            name='gabarito8',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='dojo_imersion',
            name='gabarito9',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
